version: 2
jobs:
  build:
    docker:
      - image: gkasse/electron-builder
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: Resolve dependencies
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Linting
          command: npm run lint
      - run: 
          name: Build application for Windows
          command: npm run build:win
      - store_artifacts:
          path: build/Simple-EH-Downloader.exe


